import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AssignmentCreate {
  @ApiProperty()
  user_id: string;
  @ApiProperty()
  task_id: string;
  @ApiProperty()
  assigned_at: Date;
}

export class Assignment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  user_id: string;
  @ApiProperty()
  task_id: string;
  @ApiProperty()
  assigned_at: Date;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
